# Generated by Django 5.2.6 on 2025-09-12 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='All_books',
        ),
    ]
