# Generated by Django 5.2.6 on 2025-09-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_books_all_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserv',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
