# Generated by Django 5.2.6 on 2025-09-13 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_reserv_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waitinglist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.all_books')),
            ],
        ),
    ]
