# Generated by Django 5.2.6 on 2025-09-13 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_waitinglist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='all_books',
            old_name='reservetion',
            new_name='reservation',
        ),
        migrations.RemoveField(
            model_name='reserv',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='waitinglist',
            name='name',
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
